services:
  app:
    image: gerald-lbn/refrain-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /path/to/your/music/library:/music
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - /path/to/redis/data:/data
    ports:
      - 6379:6379
