app:
  name: Refrain
  environment: "development"
  encryptionKey: ""

database:
  driver: "sqlite3"
  connection: "/data/refrain.db?_journal=WAL&_timeout=5000"

http:
  hostname: ""
  port: 8000
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"
  shutdownTimeout: "10s"
  tls:
    enabled: false
    certificate: ""
    key: ""

libraries:
  paths:
    - "/music"

tasks:
  goroutines: 10
  releaseAfter: "15m"
  cleanupInterval: "1h"
  shutdownTimeout: "10s"
