app:
  name: Refrain
  environment: "local"

database:
  driver: "sqlite3"
  connection: "/data/refrain.db"

libraries:
  paths:
    - "/music"

tasks:
  goroutines: 10
  releaseAfter: "15m"
  cleanupInterval: "1h"
  shutdownTimeout: "10s"
